### ISSUE TITLE
read_bytes_term() should raise EOFError instead of Exception

### ISSUE THREAD

**Issue by overfl0** [kaitai-io/kaitai_struct_python_runtime#41]
`read_bytes_term()` should raise EOFError instead of Exception to be consistent with `read_bytes()`.

Btw. it's funny that found this issue 1h later than the person that has reported #40 

Even if #40 is implemented using a custom class, I'd suggest having both `read_bytes_term()` and `read_bytes()` raise the same type of error.

My use case is that I'm trying to detect when the packet that I'm parsing has been truncated so it would be helpful to be able to just do `except EOFError` (or `except kaitaistruct.EOFError`) instead of having to parse the exception message.

**Comment by generalmimon** [comment]
I agree that if the terminator is required and doesn't occur before EOF, the file appears to be truncated and therefore an `EOFError`-compatible error should be thrown. I'm just not sure if it would make sense to create a specific subclass of `EOFError` just for the use in `read_bytes_term()`, because I don't know, it feels a bit like a special case. It's usually quite obvious if `EOFError` will be thrown, because it depends on just how many bytes are requested (e.g. `read_u4le` requests 4 bytes) vs. how many bytes are actually available in the stream.

With `read_bytes_term()`, it's different - you don't know in advance how many bytes it will request, because that depends on when (or if) the terminator byte occurs. Therefore, I think the error message should continue to reflect that this is a `"end of stream reached, but no terminator %d found"` error, not really a `"requested {} bytes, but only {} bytes available"` error.

Another reason why I believe this is a slightly different error than a bare `EOFError` is that the error thrown by `read_bytes_term()` can actually be suppressed using `eos-error: false` (https://doc.kaitai.io/user_guide.html#eos-error). This is not possible with normal `EOFError`s. So if a user receives a more specific error than `EOFError` in this case, they can more easily realize that they actually want the `eos-error: false` behavior.

In PHP, I added an exception class `NoTerminatorFoundError` and I think @GreyCat liked it (https://github.com/kaitai-io/kaitai_struct_php_runtime/pull/6#discussion_r379917596), so perhaps it's not a bad idea.

Does anybody (@GreyCat, @armijnhemel, @dgelessus) have an opinion on this?

**Comment by armijnhemel** [comment]
> Does anybody (@GreyCat, @armijnhemel, @dgelessus) have an opinion on this?

Personally I am agnostic to this, but it might be good to keep things consistent across the different languages. Also, if there is more information available (which seems to be the case here), then there might be users that would like to know. A subclass of `EOFError` would then be the right choice.
